[package]
name = "ihsk"
version = "0.1.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.7"
dirs-next = "2.0.0"
nix = "0.19.1"
rustyline = "7.1.0"
